### ISSUE TITLE
twilio credential environment variables do not work

### ISSUE THREAD

**Issue by danpilch** [RJPearson94/terraform-provider-twilio#22]
## Technical Details

- OS: osx
- Terraform Version: 13.*/14.0.5
- Provider Version: 0.6.1

## Affected Resources

twilio auth credential environment variables do not work

## Describe the bug

Using environment variables to pass in twilio credentials does not work

## Steps to Reproduce

Steps to reproduce the behaviour:

```
# dont use credentials in provider
provider "twilio" {}
# run terraform plan passing in env vars
TWILIO_ACCOUNT_SID=sid TWILIO_API_KEY=key terraform plan
```

## Expected behaviour

The plan should run like using credentials in `provider`

## Logs

```
Error: Account Details Specified are invalid


2021-01-22T16:32:29.494Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

**Comment by RJPearson94** [comment]
Hi @danpilch,

I have looked at the issue and the provider is working as expected. You are passing in a Twilio Account SID and Twilio API Key however the provider is expecting you to supply either of the following
- Twilio Account SID (TWILIO_ACCOUNT_SID) and Twilio Auth Token (TWILIO_AUTH_TOKEN)
- Twilio Account SID (TWILIO_ACCOUNT_SID), Twilio API Key SID (TWILIO_API_KEY) and Twilio API Secret (TWILIO_API_SECRET)

The provider doesn't support passing just an Account SID and API Key/ Secret.

The provider documentation https://registry.terraform.io/providers/RJPearson94/twilio/latest/docs contains details and examples on how to configure the provider to authenticate against the Twilio API's

Does this resolve your issue?

Finally, thanks for using the provider and any feedback is greatly appreciated.

**Comment by danpilch** [comment]
ahh damn yeah that's my fault, I didn't RTFM properly! 

thanks for making this provider, it's really helped me build a killer hackathon project at work.
