### ISSUE TITLE
cannot use account_sid and auth_token in provider configuration

### ISSUE THREAD

**Issue by danpilch** [RJPearson94/terraform-provider-twilio#27]
## Technical Details

- OS: macosx
- Terraform Version: 0.14.6
- Provider Version 0.7.1

## Affected Resources

https://github.com/RJPearson94/terraform-provider-twilio/blob/main/docs/index.md#account-sid--auth-token

## Describe the bug

Defining account_sid and auth_token in the twilio provider block does not work:

```hcl
provider "twilio" {
  account_sid = data.vault_generic_secret.twilio_dev.data["account_sid"]
  auth_token  = data.vault_generic_secret.twilio_dev.data["auth_token"]
}
```
or
```hcl
provider "twilio" {
  account_sid = "xxx"
  auth_token  = "yyy"
}
```
both do not work.

```
Acquiring state lock. This may take a few moments...
Error: Account Details Specified are invalid
```

If I use the same credentials but with

```
TWILIO_ACCOUNT_SID="" TWILIO_AUTH_TOKEN="" terraform plan
```

I can authenticate and create resources

## Steps to Reproduce

Steps to reproduce the behaviour:

1. define credentials in twilio provider block
2. `terraform plan`
3. See error

## Expected behaviour

terraform should be able to use these credentials and successfully continue without error

## Logs

 trawled the logs, nothing of use.

**Comment by RJPearson94** [comment]
hi @danpilch 

Sorry about the issue you are experiencing. I haven't been able to replicate the issue locally using the Terraform version and provider version that you have specified however let's try to triage this issue.

The error you are seeing is being returned from the underlying Go SDK (which I also maintain) and the logging is designed to prevent leakages of secrets into the logs however I acknowledge this isn't helpful when triaging issues so I will raise a separate issue on the Go SDK to investigate a better solution to this.

The SDK validation for the account credentials is limited, it only verifies the account sid is a string which starts with `AC` and the auth token is a non-blank string. The code can be seen here: https://github.com/RJPearson94/twilio-sdk-go/blob/main/session/credentials/account.go#L12-L13 

Can I confirm that you that are passing in an account sid which starts with `AC` and non-blank auth token?

**Comment by danpilch** [comment]
hi @RJPearson94 

Yes I can confirm the `account_sid` starts `ACaf` and I am passing a non-blank `auth_token`

**Comment by RJPearson94** [comment]
hey @danpilch, 

Thanks for confirming this. The SDK validation should not be triggering then. 

Would you be able to build and run the Terraform provider from the source code? This would allow me to guide you through adding some debug logging to try and triage the issue.

If this is too difficult then I am actively working on improving the SDK logging and hopefully should have a solution shortly

**Comment by RJPearson94** [comment]
hey @danpilch 

I have pushed out a new release (v0.8.0) of the provider which contains the improved error messaging for credential validation failures in the Go SDK. When a validation error occurs an error message like `Error: Account details specified are invalid. Validation errors: [SID is required, Auth token is required]` or `Error: Account details specified are invalid. Validation errors: [SID (Test) must start with AC]` will be returned.

This improved error mesage should help us identify what validation failure is causing your issue. Please update your provider config to the following:

```
terraform {
  required_providers {
    twilio = {
      source  = "RJPearson94/twilio"
      version = ">= 0.8.0"
    }
  }
}
```

Once you have upgraded, can you please paste the error message you get (please redact your account sid i.e. substitute an x for each character after the AC) and then I can continue assisting with the triage process

**Comment by danpilch** [comment]
OK I upgraded, cut out remote state and vault lookup and retried, this time I get this error:

`Error: Account details specified are invalid. Validation errors: [SID is required, Auth token is required]`

I define the credentials in versions.tf:
```hcl
terraform {
  required_version = ">= 0.14"

  required_providers {
    twilio = {
      source      = "RJPearson94/twilio"
      version     = ">= 0.8.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 2.18.0"
    }
  }
}

provider "twilio" {
  account_sid = "ACxx"
  auth_token = "xx"
}
```

please see attached trace logs `out.log`:
[out.log](https://github.com/RJPearson94/terraform-provider-twilio/files/6008823/out.log)

**Comment by RJPearson94** [comment]
Hi @danpilch 

No worries, I'm happy to help and thank you for using the provider.

Thanks for sharing the logs, I'm not sure the error doesn't show in the logs but the logs helped gain some insight into the structure of your Terraform code.

I think I may know what is causing your issue.

From the logs, I can see you have a module called `twilio_emea_dpilch` which has a source of  `../modules/twilio/twilio-emea-sms-proxy`. This module references several resources and data sources from the Twilio provider. The logs suggest you also have a provider (possibly with default configuration) defined in the module and you may or may not be specifying the required provider versions.

When I say a provider using its default configuration, I mean a provider defined with no configuration specified i.e.

```hcl
provider "twilio" {}
```

You then are calling your module from another Terraform configuration file where you are specifying the required versions and provider configuration (with the `account_sid` and `auth_token`) hardcoded.

Your setup may look something like this

```
+-- modules
|   +-- twilio
|       +-- twilio-emea-sms-proxy
|           +-- main.tf
|           +-- versions.tf
|           +-- providers.tf
|           +-- ...
|       +-- ...
|   +-- ...
+-- emea
|   +-- main.tf
|   +-- versions.tf
|   +-- providers.tf
|   +-- ...
```

If this setup is correct, I suspect the error you are seeing is from the child provider inside the module (modules/twilio/twilio-emea-sms-proxy/providers.tf) not the parent provider (emea/providers.tf). If you are specifying a provider using its default configuration, the provider will execute fallback functions to set the configuration using environment variables. If no value is found for the environment variable then a default of nil is set. These credentials are then used to initialise the Go SDK which is where the validation takes place.

As the provider falls back to the environment variables, this would explain why your Terraform code worked when specifying the Account SID and Auth Token as environment variables on the command line. As the child provider executed its fallback function and set the account SID and Auth Token from the corresponding environment variables.

Terraform can pass a configured parent provider to child modules automatically (See the [Terraform Providers Within Modules docs](https://www.terraform.io/docs/language/modules/develop/providers.html) for more information)

If my assumption is correct you should be able to delete the default provider in the module and the issue should be resolved.

Let me know if that work or if you have an edge case which means you need to specify the provider in the module

**Comment by danpilch** [comment]
You're totally right, I had `provider "twilio" {}` in the parent module! I forgot about that, my fault... 

It is now working properly! thank you @RJPearson94 !

**Comment by RJPearson94** [comment]
No worries @danpilch, happy to help. Glad it is now working.

As always if you have any issues feel free to raise an issue and I'll try my best to assist
