### ISSUE TITLE
Add possibility to set recording settings

### ISSUE THREAD

**Issue by thomaschaaf** [RJPearson94/terraform-provider-twilio#35]
## Is your feature request related to a problem

I would like to use encrypted recordings: https://www.twilio.com/docs/video/api/encrypted-recordings#http-post for this I need to create public keys: https://www.twilio.com/docs/iam/credentials/api I would like to manage that in code.

## Describe the solution you'd like

Use the APIs to first make it possible to create public keys and second make it possible to set the encrypted recordings

**Comment by RJPearson94** [comment]
hi @thomaschaaf,

Thanks for raising this feature request. I will take a look at implementing the changes you have asked for, at this time I cannot give an ETA for this feature but I'll take a look at implementing it. 

Just so you are aware as encrypted recordings are an enterprise feature I won't be able to add the usually level of testing to the resources as I don't have access to a Twilio Enterprise account. 

Thank again for the feature request and any additional feedback on the provider would be greatly appreciated

**Comment by thomaschaaf** [comment]
Hello,

I actually just saw that I wanted to set voice recording encryption but I can't find an API for that. But managing the public keys would already be awesome.

Thomas

**Comment by RJPearson94** [comment]
hey @thomaschaaf,

Thanks for getting back to me. I just had a quick look through the Twilio documentation and [OpenAPI documents](https://github.com/twilio/twilio-oai) and I couldn't find any API which would allow the voice recording to be configured. It might be worth asking Twilio if its a console only feature via either a support case or by asking a question on the [Twilio Community Forum](https://community.twilio.com/community/) 

I will look at adding public key support. Can I confirm you didn't intend to ask for video encryption support in the provider and only want programmable voice encryption support (subject to support in the public API)?

**Comment by RJPearson94** [comment]
hi @thomaschaaf,

I have added the ability to manage public keys via the Terraform provider, the docs are [here](https://github.com/RJPearson94/terraform-provider-twilio/blob/main/docs/resources/credentials_public_key.md)

I have also added the ability to manage Twilio Video [composition settings](https://github.com/RJPearson94/terraform-provider-twilio/blob/main/docs/resources/video_composition_settings.md) and [recording settings](https://github.com/RJPearson94/terraform-provider-twilio/blob/main/docs/resources/video_recording_settings.md) via the provider too.

I'm not sure if you plan to store recordings in your S3 buckets but I have added the ability to manage AWS credentials via the provider, the docs are [here](https://github.com/RJPearson94/terraform-provider-twilio/blob/main/docs/resources/credentials_aws.md) if you plan to use this feature

These new resources have been released as part of v0.14.0 which is now available in the Terraform Registry.

Please update your Terraform configuration to include the following

```
terraform {
  required_providers {
    twilio = {
      source = "RJPearson94/twilio"
      version = ">= 0.14.0"
    }
  }
}
```

I have performed some testing on this however as I don't have an Enterprise account, the testing on the video composition and recording settings is limited. If you have any issues with the resources then feel free to raise another issue.

Did you manage to find out if you can configure Programmable Voice recording encryption via the public API?
Is this feature request now resolved?

**Comment by thomaschaaf** [comment]
@RJPearson94 thank you a lot. I am asking the twilio support for an api for the other thing. Maybe they can provide me with the needed infos.

**Comment by RJPearson94** [comment]
Hi @thomaschaaf, Did you manage to find out if you can configure Programmable Voice recording encryption via the public API?

**Comment by thomaschaaf** [comment]
I have reached out to twilio but not received an answer yet.

**Comment by RJPearson94** [comment]
Ok, thanks for the update @thomaschaaf. When you do hear can you let me know as I’m curious if this can be done or not

**Comment by RJPearson94** [comment]
Hi @thomaschaaf, did you hear back from Twilio about whether recording encryption can be configured via the Programmable Voice API? 
If it cannot be configured via the public API, is this issue resolved now?

**Comment by thomaschaaf** [comment]
I have closed it 🙂 sadly they didn't respond

**Comment by RJPearson94** [comment]
sorry to hear they didn't respond but thank you for closing the issue
