### ISSUE TITLE
Rotate Auth Token

### ISSUE THREAD

**Issue by enchorb** [RJPearson94/terraform-provider-twilio#62]
Hey,  is there anyway to rotate the auth_token for a sub account using this provider. 

I do see Twilio has an API for it here: https://www.twilio.com/docs/iam/api/authtoken

This could be useful in combination with Terraform time rotating feature or if a secret is exposed without having to update the token manually and re-import the resource.

**Comment by RJPearson94** [comment]
Hi @enchorb, Apologies for the slow response.

Currently, this is not supported by the provider, I'm curious to get your thoughts on how this would work as I'm not too sure how this would be implemented, I have a couple of questions:

1. Would you expect this to be part of the twilio_account_sub_account resource or a new resource?
2. How would you expect to trigger the rotation, by setting a rotate auth token attribute, tainting the resource or passing in metadata/ hash i.e. some providers use etags to conditionally force a resource to recreate however in this context it would cause the key rotation 
3. I'm curious to understand your use case for auth tokens a bit more, as I would have thought your use case better suits using API keys which you can then taint using terraform to force the recreation

Kind Regards
Rob

**Comment by enchorb** [comment]
Hi Rob, thanks for the response. I completely forgot about API keys in Twilio, will proceed with using those instead!
