### ISSUE TITLE
Verify Message Template Not Applying

### ISSUE THREAD

**Issue by enchorb** [RJPearson94/terraform-provider-twilio#63]
When specifying a `default_template_sid` for the `twilio_verify_service` resource, the Terraform apply is successful but inside Twilio it never actually gets set, and when re-running Terraform apply it lists the `default_template_sid` as a configuration change again.

For more context I am trying to apply the `HJ1552d2ed1b7588baf459dee4acaa0b2b` template (Static Verify Templates Brandful)

**Comment by RJPearson94** [comment]
Hi @enchorb, 

Apologies for this, it is a bug in the resource. The attribute was not being set on either create or update. This has been corrected now.

This fix has been released as part of v0.19.1 which is now available in the Terraform Registry.

Please update your Terraform configuration to include the following

terraform {
  required_providers {
    twilio = {
      source = "RJPearson94/twilio"
      version = "0.19.1"
    }
  }
} 

Kind Regards
Rob

**Comment by enchorb** [comment]
Thanks for the quick fix @RJPearson94!
