### ISSUE TITLE
Importing a Twilio phone number doesn't populate its area code

### ISSUE THREAD

**Issue by egwynn** [RJPearson94/terraform-provider-twilio#79]
## Technical Details

- OS: MacOS
- Terraform Version: 1.4
- Provider Version v0.18.18

## Affected Resources

- `twilio_api_accounts_incoming_phone_numbers`

## Describe the bug

If you import a Twilio phone number, the terraform state will always set that number's `area_code` to `null`.

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Create a Twilio phone number
2. Import same
3. Locate resource in the terraform state
4. Notice that its `area_code` is set to `null`

## Expected behaviour

The provider should populate the `area_code` based on what is returned by the Twilio API

## Logs

N/A

## Additional context

I believe [this block](https://github.com/RJPearson94/terraform-provider-twilio/blob/906f1c879be5c15401bec04c7926c8077d502069/twilio/internal/services/phone_number/resource_phone_number.go#L546-L563) should simply include a line for the `area_code` field.

**Comment by RJPearson94** [comment]
Hi @egwynn,

Can I just double check that you are using my version of the provider? as the information you shared points to an issue with the official Twilio Terraform provider, this was developed before the Twilio one existed.

As the resource you referenced twilio_api_accounts_incoming_phone_numbers doesn't exist in the provider. The corresponding version in my provider is named twilio_phone_number, the documentation is https://registry.terraform.io/providers/RJPearson94/twilio/latest/docs/resources/phone_number

If this is meant to be raised for official Terraform provider, the repo is https://github.com/twilio/terraform-provider-twilio.
If I have misunderstood anything please correct, I am also happy to provide and help and assistance using resources that are within the current provider

Rob

**Comment by egwynn** [comment]
@RJPearson94 you're totally right, I was mistaken about which provider I was using! Thanks for the insights.
