### ISSUE TITLE
Importing a Twilio phone number's assignment in a messaging service doesn't populate its phone_number_sid field

### ISSUE THREAD

**Issue by egwynn** [RJPearson94/terraform-provider-twilio#80]
## Technical Details

- OS: MacOS
- Terraform Version: 1.4
- Provider Version v0.18.18

## Affected Resources

- ` twilio_messaging_services_phone_numbers_v1`

## Describe the bug

If you import a Twilio messaging service phone number, the terraform state will always set that number's `phone_number_sid ` to `null`.

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Create a Twilio messaging service, phone number, and add the number to the service.
2. Import all 3 from above
3. Locate `twilio_messaging_services_phone_numbers_v1` resource in the terraform state
4. Notice that its `phone_number_sid` is set to `null`

## Expected behaviour

The provider should populate the `phone_number_sid` based on what is returned by the Twilio API

## Logs

N/A

## Additional context

I believe [this block](https://github.com/RJPearson94/terraform-provider-twilio/blob/906f1c879be5c15401bec04c7926c8077d502069/twilio/internal/services/messaging/resource_messaging_phone_number.go#L121-L127) should simply include a line for the `phone_number_sid ` field.

**Comment by RJPearson94** [comment]
Hi @egwynn,

Can I just double check that you are using my version of the provider? as the information you shared points to an issue with the official Twilio Terraform provider, this was developed before the Twilio one existed. 

As the resource you referenced `twilio_messaging_services_phone_numbers_v1` doesn't exist in the provider. The corresponding version in my provider is named `twilio_messaging_phone_number`, the documentation is https://registry.terraform.io/providers/RJPearson94/twilio/latest/docs/resources/messaging_phone_number

If this is meant to be raised for official Terraform provider, the repo is https://github.com/twilio/terraform-provider-twilio. 
If I have misunderstood anything please correct, I am also happy to provide and help and assistance using resources that are within the current provider

Rob
