### ISSUE TITLE
Signature: openpgp: key expired

### ISSUE THREAD

**Issue by lucas-felinto** [RJPearson94/terraform-provider-twilio#84]
## Technical Details

- Terraform Version: v0.12.26
- Provider Version v0.23.0

## Affected Resources

- RJPearson94/twilio

## Describe the bug

Hello there! We are facing a failing to install the provider running terraform-apply, looks like the openpgp is expired, how can we fix it? 

## Steps to Reproduce

Run terraform-apply

## Expected behavior

Success on provider install

## Logs

```
Initializing provider plugins...
- Reusing previous version of twilio/twilio from the dependency lock file
- Reusing previous version of rjpearson94/twilio from the dependency lock file
- Installing twilio/twilio v0.18.25...
- Installed twilio/twilio v0.18.25 (self-signed, key ID 2D8261056119B780)
- Installing rjpearson94/twilio v0.23.0...
╷
│ Error: Failed to install provider
│ 

│ Error while installing rjpearson94/twilio v0.23.0: error checking
│ signature: openpgp: key expired
╵

make: *** [Makefile:[114](https://github.com/twilio/tdp-foundational-demo/actions/runs/6431506450/job/17464549441#step:7:115): terraform-init] Error 1
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Error: Process completed with exit code 2.
```

## Additional context

We are running it into a GitHub Actions pipeline

**Comment by RJPearson94** [comment]
Hi @lucas-felinto,

Apologies you have run into this issue and apologies for the slow response.

This is a weird issue, as I have checked the key, and it was set to never expire, so you shouldn't have seen this issue.
Nonetheless, I have managed to replicate the issue locally though.

To resolve this issue, I have generated a new GPG key which all future versions of the provider will be signed with. The key ID for this is E829FA5CF6F67ECC
I have pushed a new version of the provider (0.25.0) to the registry which is signed with this new key, please update your Terraform to include the following

```
terraform {
  required_version = ">= 0.13"

  required_providers {
    twilio = {
      source  = "RJPearson94/twilio"
      version = ">= 0.25.0"
    }
  }
}
```

This should resolve your issue but if the issue persists then please reach out, and I will try to assist.
Apologies again for this issue and any inconvenience this may have caused.

Kind Regards
Rob

**Comment by lucas-felinto** [comment]
Hey @RJPearson94,

Thank you so much for your support! We've update our Terraform and the deploy works fine! 

The Twilio Demo Platform Team appreciate your help! 😃

**Comment by RJPearson94** [comment]
No problem, glad I could help @lucas-felinto.

Thanks again for using the provider.
