### ISSUE TITLE
Twilio Studio Flow creation failing, resource created but not added to state

### ISSUE THREAD

**Issue by willhannigan** [RJPearson94/terraform-provider-twilio#86]
## Technical Details

- OS: Linux
- Terraform Version: 1.3.4
- Provider Version: 0.2.1

## Affected Resources

- twilio_studio_flow

## Describe the bug

When creating a new studio flow the flow is created in Twilio but an error is thrown and the resource is not added into the terraform state. So when re-running the apply command, it attempts to recreate the flow with the same error again. 

We are working around this issue to import the created resource into the state, the resource is then updated in place on the next apply.

This is the error that is thrown:
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.twilio.twilio_studio_flow.${STUDIO_FLOW_NAME}, provider
│ "module.twillio.provider[\"[registry.terraform.io/rjpearson94/twilio\"]"](http://registry.terraform.io/rjpearson94/twilio])
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Add a new twilio_studio_flow resource to your plan
2. Run terraform apply
3. See error

## Expected behaviour

Studio flow to be created, apply command to run successfully and resource added to terraform state

**Comment by RJPearson94** [comment]
hi @willhannigan,

Sorry, you have run into this issue. 

Can I check that you are using v0.2.1 of the Terraform provider? The provider is currently on v0.25.0, which has a number of bug fixes, including fixes for Studio. 
I haven't been able to replicate this issue with the latest version of the provider using the examples in the repo 
[flex webchat](https://github.com/RJPearson94/terraform-provider-twilio/tree/main/examples/studio/flow/flex-webchat) 
[basic flow](https://github.com/RJPearson94/terraform-provider-twilio/tree/main/examples/studio/flow/basic)

If you are using v0.2.1, I would recommend upgrading to the latest provider version (v0.25.0) and re-run the terraform and see if you get the same issue.

If this doesn't work then I can try to assist further

Kind Regards
Rob

**Comment by RJPearson94** [comment]
Hi @willhannigan,

On "Our definition is using a template file that injects SID's from other resources that have already been created, could this cause an issue?"

This should be fine, as I do that on a number of different projects. An example can be seen at https://github.com/RJPearson94/terraform-provider-twilio/blob/main/examples/studio/flow/flex-webchat/main.tf 
Do you have the validate attribute set to true? I'm just wondering if the JSON isn't valid for Studio i.e. a value isn't substituted correctly so it's throwing an error in an unexpected place.

Is the terraform shareable? As that would aid with debugging. no problem if not. Are you able to tell me what values are being substituted into the JSON and i can try replicate it myself

Kind Regards

**Comment by RJPearson94** [comment]
I have also noticed that Studio does occasionally have issues with commit messages. so I would recommend always supplying a commit message if you're not already

**Comment by RJPearson94** [comment]
Hi @willhannigan,pi

I did manage to replicate this within the tests. It appears to be a quirk with the commit message. The provider wasn't correctly clearing down the commit message, but the API does seem to struggle when an empty string is passing in the commit message.

I am going to set a default commit message of "Updated via Terraform" to ensure a commit message is always passed, and this should mitigate this issues

**Comment by RJPearson94** [comment]
Hi @willhannigan,

I have pushed out a new version of the Terraform provider to try and resolve this issue. Can you update your terraform to include the following and see if the issue persists?

```tf
terraform {
  required_version = ">= 0.13"

  required_providers {
    twilio = {
      source  = "RJPearson94/twilio"
      version = ">= 0.25.0"
    }
  }
}
```

Kind Regards
Rob

**Comment by willhannigan** [comment]
Hi @RJPearson94

This has fixed our issue. 

Thank you very much. Great work on this provider it has really helped us with our migration to Twilio.

Kind regards
Will

**Comment by willhannigan** [comment]
Hi @RJPearson94 

Turns out this hasn't fixed our issue after all, apologies for false alarm!

We deployed our plan to our staging Twilio account and the apply completed successfully and the flow was created. However, when we deployed to the production account the same error occurred.

We have just tried again with a really simple flow (see below) and we still get the same error. Any ideas what might be causing this?

```
resource "twilio_studio_flow" "studio_flow_test" {
  commit_message = "Terraform create"
  friendly_name = "Test terraform flow creation"
  status = "published"
  definition = jsonencode({
    "description": "Test Flow",
    "states": [
      {
        "name": "Trigger",
        "type": "trigger",
        "transitions": [],
        "properties": {
          "offset": {
            "x": 0,
            "y": 0
          }
        }
      }
    ],
    "initial_state": "Trigger",
    "flags": {
      "allow_concurrent_calls": true
    }
  })
  validate = "true"
}
```

**Comment by RJPearson94** [comment]
Hi @willhannigan,

Hmm, I'm looking into this. 
I'm not 100% sure whether it's the provider or if the API is returning something unexpected, which is throwing it off. As I am struggling to replicate it with the simple flow.
It is also strange it worked on staging but not production.

Will continue digging

Kind Regards
Rob

**Comment by RJPearson94** [comment]
HI @willhannigan,

Apologies for the slow response.

I think I may have gotten to the bottom of this issue; it looks like it is caused by the Studio Flow API being eventually consistent. This explains why the issue appears to be intermittent as well, as sometimes the service is fast enough to return the correct data other times, it is not.

This issue has occurred due to the way the provider has been configured; when the provider creates or updates a resource, it calls the corresponding function on the resource, which in turn calls the API, passing the necessary data however, instead of updating the terraform state from the response it calls the GET endpoint to populate the state. This is a pattern that is adopted by other providers to ensure the state is updated consistently. 

The Terraform provider appears to be fetching data before the service has been updated. During testing, I have seen 404s occur when fetching the flow, and the API return stale data after the data has been updated. I will modify this resource to store the output that is returned when the resource is created or modified. This should help mitigate this issue.

Kind Regards
Rob

**Comment by RJPearson94** [comment]
Hi @willhannigan,

I have pushed out a new version of the Terraform provider to try and resolve this issue. Can you update your terraform to include the following and see if the issue persists?

```tf
terraform {
  required_version = ">= 0.13"

  required_providers {
    twilio = {
      source  = "RJPearson94/twilio"
      version = ">= 0.26.1"
    }
  }
}
```

Kind Regards
Rob

**Comment by RJPearson94** [comment]
hi @willhannigan,

Just following up, have you managed to test this new version and has this resolved your issue?

Kind Regards
Rob

**Comment by willhannigan** [comment]
Hi @RJPearson94 
Apologies was waiting for a release to production to confirm it worked. Yes all good, thank you for your help

**Comment by RJPearson94** [comment]
Hi @willhannigan,

No problem, glad this has been resolved. 
Thanks for using the provider.

Kind Regards
Rob
